name: Deploy Strapi to AWS ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY_NAME: strapi-app-karthik
      AWS_ACCOUNT_ID: 118273046134
      ECR_URI: 118273046134.dkr.ecr.us-east-1.amazonaws.com/strapi-app-karthik

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Create ECR repository if it doesn't exist
      run: |
        aws ecr describe-repositories --repository-names $ECR_REPOSITORY_NAME || \
        aws ecr create-repository --repository-name $ECR_REPOSITORY_NAME

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password | docker login --username AWS --password-stdin ${{ env.ECR_URI }}

    - name: Build and push Docker image
      run: |
        docker build -t $ECR_REPOSITORY_NAME ./docker
        docker tag $ECR_REPOSITORY_NAME:latest $ECR_URI:latest
        docker push $ECR_URI:latest

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Terraform Init and Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve

    - name: Wait for 10 minutes
      if: always()
      run: sleep 600
  
    - name: Terraform Destroy
      if: always()
      run: |
        cd terraform
        terraform destroy -auto-approve

